### PR TITLE
API for enabling flushing after log

### PR DESCRIPTION
**Pull request by nsahu910**
RDKTV-11982 : enableLogsFlushing and getLogsFlushingEnabled fails

Reason for change: defining enableLogsFlushing and getLogsFlushingEnabled.

### CODE REVIEW

**Comment by nsahu910** [comment]
Hi @anand-ky,
can you please review this.

**Comment by anand-ky** [comment]
@binuinbaraj - Pls review.

@nsahu910 - Pls sign Contributor License Agreement.

**Comment by nsahu910** [comment]
hi @anand-ky 
i have signed Contributor License Agreement

**Comment by binuinbaraj** [comment]
@Anand Kandasamy  I reviewed and the changes look good. 
    On Wednesday, 1 December 2021, 06:26:33 AM GMT-5, Anand Kandasamy ***@***.***> wrote:  
 
 


@binuinbaraj - Pls review.

@nsahu910 - Pls sign Contributor License Agreement.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
