### PR TITLE
Workaround for the race condition in bmalloc's BMScavenger caused by …

### PR DESCRIPTION
**Pull request by GlebNovodranPE**
…WebKitBrowser plugin implementation unloading.

Sometimes BMScavenger crashes with a SIGSEGV  in __pthread_cond_timedwait after WebKitBrowserPlugin implementation is unloaded, as it  retains an invalidated condition variable.

The crashed thread callstack usually looks like:
```
5|0|libpthread-2.31.so|__condvar_dec_grefs|/usr/src/debug/glibc/2.31+gitAUTOINC+1094741224-r0/git/nptl/pthread_cond_wait.c|153|0x0
5|1|libpthread-2.31.so|__pthread_cond_timedwait|/usr/src/debug/glibc/2.31+gitAUTOINC+1094741224-r0/git/nptl/pthread_cond_wait.c|530|0x3
5|2|||||0xb21504e9
5|3|libstdc++.so.6.0.28|std::execute_native_thread_routine|/usr/src/debug/gcc-runtime/9.3.0-r0/arm-rdk-linux-gnueabi/libstdc++-v3/src/c++11/../../../../../../../../../../work-shared/gcc-9.3.0-r0/gcc-9.3.0/libstdc++-v3/src/c++11/thread.cc|80|0x3
5|4|libpthread-2.31.so|start_thread|/usr/src/debug/glibc/2.31+gitAUTOINC+1094741224-r0/git/nptl/pthread_create.c|477|0x1

```

This workaround is to prevent the plugin implementation unloading.

### CODE REVIEW

**Comment by GlebNovodranPE** [comment]
@binuinbaraj , would you please review this?

**Review by emutavchi — APPROVED** [review]

**Comment by emutavchi** [comment]
@modeveci could you please review as well?

**Review by binuinbaraj — DISMISSED** [review]

**Comment by modeveci** [comment]
@GlebNovodranPE , I will talk with browser team regarding this issue:
_Sometimes BMScavenger crashes with a SIGSEGV in __pthread_cond_timedwait after WebKitBrowserPlugin implementation is unloaded, as it retains an invalidated condition variable._

What do you mean by this preventing? When Thunder framework deactives plugin, what will happen?

@MFransen69 , could you please look at this PR?

**Comment by MFransen69** [comment]
Hi @GlebNovodranPE 

Could you please explain a bit more on what BMScavenger is (googled but could not find much, guess it is a issue/leak detection tooL)? What processes is it attached to? (is in instrumented in, in the build or just an external tool?)  e.g. to the in process part of the plugin (Thunder/WPEFramework), the OOP part (WPEProcess) or the Webkit processes itself?
And if you have this issue with Webkit don't you then have it also with other plugins or is BMScavenger  only used for Webkit?
Like in your description it really sounds like a workaround. Unloading the libraries when a plugin is deactivated is an integral part of the Thunder architecture, e.g. for memory constraints, guaranteed correct (static) initialization, library replacement and not doing so will for example break our automated QA tools (we actually test this). So to me looks better to fix the underlying issue that deactivating the plugin works correctly also when BMScavenger is used.

**Comment by glebnovodran** [comment]
@modeveci ,

> When Thunder framework deactives plugin, what will happen?

Sometimes bmalloc's BMScavenger crashes executing 
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/nptl/pthread_cond_wait.c#L153

Looks like condition is invalidated after the library is unloaded, but bmalloc's BMScavenger attempts to operate with it even though it is already invalid.

The crash can be reproduced by launching an html app and a lightning app one after another.

**Review by emutavchi — APPROVED** [review]

**Pull request merged**
