### PR TITLE
ONEM-23352: Module.h included before core and  interfaces includes

### PR DESCRIPTION
**Pull request by mikolaj-staworzynski-red**

### CODE REVIEW

**Review by emutavchi — CHANGES_REQUESTED** [review]
@mikolaj-staworzynski-red thanks for the PR. Could you please submit again 2201 sprint branch?

**Comment by pradeeptakdas** [comment]
@mikolaj-staworzynski-red - Can you please submit to the latest running sprint/2203 branch?

**Comment by mikolaj-staworzynski-red** [comment]
> @mikolaj-staworzynski-red - Can you please submit to the latest running sprint/2203 branch?

Done here: https://github.com/rdkcentral/rdkservices/pull/2333

**Comment by Firdose2109** [comment]
Can one of the admins verify this patch?

**Comment by mikolaj-staworzynski-red** [comment]
Obsolete: submitted to sprint/2203 here: https://github.com/rdkcentral/rdkservices/pull/2333

**Pull request closed without merging**
