### PR TITLE
RDK-52231 Add SharedStorage plugin

### PR DESCRIPTION
**Pull request by srikanth-vv**
Reason for change: Added new plugin
Test Procedure: SharedStorage APIs
Risks: Low
Priority: P1

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
Checked this pr...
1. In plugins there is IShell, why do you use RPC::CommunicatorClient in plugins?
2. Is AddRef needed after QueryInterface?
3. RemoteConnectionNotification is not relevant for in-process.
4. Please use Thunder logging, https://rdkcentral.github.io/Thunder/plugin/messaging/
5. Do not log keys, values, etc, this violates "security" of "secure" store
6. _adminLock makes all APIs synced, this does not make sense.
7. Please remove trash logging like "status success".
8. Why need find_package(IARMBus)?

**Comment by srikanth-vv** [comment]
@npoltorapavlo : Changed Persistent Calls to "QueryInterfaceByCallsign" and cleaned up the code.

**Comment by npoltorapavlo** [comment]
@srikanth-vv  1, 7. RPC::CommunicatorClient is not needed in your code. `LOGINFO("Scope: %d"` , `LOGINFO("ValueChanged")` , `_T("ValueChanged event")` will pollute the logs with useless lines.

**Comment by srikanth-vv** [comment]
@npoltorapavlo : Removed RPC::CommunicatorClient and added Logs in case of errors.

**Comment by npoltorapavlo** [comment]
Looks good

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
