### PR TITLE
RDKDEV-1011: Upstream change to support HdmiCecSink plugin and add sendWakeupMessage method

### PR DESCRIPTION
**Pull request by jithajamesp**
Reason for change: Fix the HdmiCecSink one-click wake up issue.

Test Procedure: Ensure that the curl commands return expected responses

Risks: Low

Signed-off-by: lanyujie <lanyujie@skyworth.com>

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4817

**Comment by viveksinghnarwaria** [comment]
Please resync the private branch

**Comment by jithajamesp** [comment]
> Please resync the private branch

Done

**Comment by jithajamesp** [comment]
Abandoning these changes since these are only applicable for non-tv platforms.

**Pull request closed without merging**
