### PR TITLE
RDK-42088 : Avoid getMaintenanceStartTime.sh script for starttime res…

### PR DESCRIPTION
**Pull request by V3110**
…ponse

Reason for change: Update the starttime from DCM written to /opt/rdk_maintenance.conf file
Test Procedure: NA
Risks: None
Priority: P2

### CODE REVIEW

**Comment by tdeva14** [comment]
As discussed, lets ensure we maintain parity with the script and not change the functionality

**Review by tdeva14 — CHANGES_REQUESTED** [review]
Please stick to the logic in script

**Comment by V3110** [comment]
Corrected the changes as discussed and now calculating the starttime whenever requested by maintenance manager based on values from rdk_maintenance.conf file

**Comment by anand-ky** [comment]
Closing older PRs. Pls bring it to latest sprint/main branches if required.

**Pull request closed without merging**
