### PR TITLE
Updated .json and .md files

### PR DESCRIPTION
**Pull request by RKarthikeyanRaja**
Updated the WifiManger .json and .md files as per the latest code.
JIRA ID: https://ccp.sys.comcast.net/browse/RDK-33853

@anand-ky 
Dev Owner Tony has approved in this link: https://github.com/rdkcentral/rdkservices/pull/1904 . Created a new request addressing conflicts. Please merge this request.

### CODE REVIEW

**Review by tabbas651 — COMMENTED** [review]
please find the review Comments
- link is not working for  WifiManager.json, it returns 404 value
- can you please modify like "A result value of 0" instead of "A 0 value" in mentioned methods
- please remove  version -2 in initiateWPSPairing because you removed that statement for getSupportedSecurityModes otherwise add the version-2 for getSupportedSecurityModes

**Comment by RKarthikeyanRaja** [comment]
@tabbas651 For the first comment "link is not working for WifiManager.json, it returns 404 value". 

It is an autogenerated [URL]
(https://github.com/rdkcentral/ThunderInterfaces/tree/master/interfaces/WifiManager.json) while generating the WifiManager.md file using JsonGenerator.py script file. The weblink which is created is not proper in the  JsonGenerator.py script file. Please check this [https://github.com/rdkcentral/Thunder/blob/master/Tools/JsonGenerator/JsonGenerator.py#L2930](url) where the script for weblink generation is handled.

**Comment by RKarthikeyanRaja** [comment]
> please find the review Comments
> 
> * link is not working for  WifiManager.json, it returns 404 value
> * can you please modify like "A result value of 0" instead of "A 0 value" in mentioned methods
> * please remove  version -2 in initiateWPSPairing because you removed that statement for getSupportedSecurityModes otherwise add the version-2 for getSupportedSecurityModes

**Comment by RKarthikeyanRaja** [comment]
By mistake closed this PR. Reopening now.

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
