### PR TITLE
Utils separation of concern

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Split omniscient utils.
Remove "utils.h" and "utils.cpp".
Fix Network/NetUtils.h - include "Module.h".
Fix Network/NetUtilsNetlink.h - include "Module.h".
Fix SystemAudioPlayer/test/SAPThunderAPITest.cpp - add MODULE_NAME_DECLARATION.
Fix SystemServices/SystemServicesHelper.h - include "Module.h".
Fix helpers/WebSockets/CommunicationInterface/BinaryInterface.h - include "Module.h".
Fix helpers/WebSockets/CommunicationInterface/CommandInterface.h - include "Module.h".
Fix helpers/WebSockets/CommunicationInterface/JsonRpcInterface.h - include "Module.h".
Fix helpers/WebSockets/Encryption/NoEncryption.h - include "Module.h".
Fix helpers/WebSockets/Encryption/TlsEnabled.h - include "Module.h".
Fix helpers/WebSockets/JsonRpc/Notification.h - include "Module.h".
Fix helpers/WebSockets/JsonRpc/Request.h - include "Module.h".
Fix helpers/WebSockets/JsonRpc/Response.h - include "Module.h".
Fix helpers/WebSockets/PingPong/PingPongEnabled.h - include "Module.h".
Fix helpers/WebSockets/Roles/Client.h - include "Module.h".
Fix helpers/WebSockets/Roles/SingleClientServer.h - include "Module.h".
Fix helpers/cSettings.h - add #pragma once.

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
for https://github.com/rdkcentral/rdkservices/issues/2319

**Comment by npoltorapavlo** [comment]
https://gerrit.teamccp.com/#/c/668059/

**Comment by npoltorapavlo** [comment]
image size improvement:
SKYXIONE-SKY-Yocto-Build/79331 - difference:-176128 Bytes
ARRISXG1V4-Yocto-Build/236733 - difference:-127040 Bytes
PACEXI5-Yocto-Build/277101 - difference:-131068 Bytes
ARRISXI6-Yocto-Build/216019 - difference:-127472 Bytes
...

**Comment by npoltorapavlo** [comment]
Included https://github.com/rdkcentral/rdkservices/pull/2999 here

**Review by anand-ky — APPROVED** [review]

**Comment by anand-ky** [comment]
Looks good. Nice to see image size improvements!

**Pull request merged**
