### PR TITLE
METROL-341: Outofprocess config cleanup to Mode

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Comment by HaseenaSainul** [comment]
PR created against latest sprint (this is created based on the comment in the closed PR: https://github.com/rdkcentral/rdkservices/pull/1821)

**Review by MFransen69 — APPROVED** [review]

**Comment by anand-ky** [comment]
@emutavchi - Pls review.

**Comment by emutavchi** [comment]
browser changes looks good to me. Not sure how "mode" configuration would impact containerization. @goruklu could you please review as well?

@anand-ky somebody else should review changes in other services.

**Review by goruklu — APPROVED** [review]

**Comment by goruklu** [comment]
@emutavchi   @anand-ky  I'm good with these changes. The changes to the "mode" parameter was done for containerization purposes originally and our code handles "mode=local" or "mode=out-of-process" similarly.

**Review by anand-ky — APPROVED** [review]
thanks guys. Reviewed the other changes and it looks good.

**Comment by pradeeptakdas** [comment]
Internal JIRA for tracking https://ccp.sys.comcast.net/browse/RDKCOM-2903

**Pull request merged**
