### PR TITLE
RDKTV-12796:Move iarmmgrs oem patches

### PR DESCRIPTION
**Pull request by lakshmiravishankar**

### CODE REVIEW

**Comment by manojmani1394** [comment]
@apatel859  Please help merge after RM confirmation.

**Comment by apatel859** [comment]
> @apatel859 Please help merge after RM confirmation.

the jira is not yet verified . after that it should go to RM approval

**Comment by manojmani1394** [comment]
@apatel859 the changes are now approved to be merged to xumo_1. Please help merge this change

**Review by apatel859 — CHANGES_REQUESTED** [review]
https://github.com/rdkcentral/rdkservices/pull/4015 add changes from this as well to this

**Review by apatel859 — APPROVED** [review]

**Review by apatel859 — CHANGES_REQUESTED** [review]
update version number

**Comment by anand-ky** [comment]
Closing older PRs. Pls bring to latest sprint or topic branch.

**Pull request closed without merging**
