### PR TITLE
RDK-35521: Add Unit Tests for DataCapture using Google Test Framework

### PR DESCRIPTION
**Pull request by mateusz-adamski-red**
Signed-off-by: mateusz.adamski <mateusz.adamski2@sky.uk>

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
@mateusz-adamski-red, please avoid changing the plugin's code unless it is a fix. There's no need to change socket_adaptor or DataCapture. By mocking socket_adaptor you skip testing socket_adaptor which is an important part of the plugin. So please remove SocketAdaptorMock and add a dummy websocket server. Pass its address as dataLocator. All IARM_Bus_Call-s should have expectations. There's no need to duplicate tests, for example, getAudioClip can be tested 1 time instead of 5 times.

**Comment by npoltorapavlo** [comment]
The test is passing although it's not working correctly. For example, `POST / HTTP/1.1 200` isn't a valid HTTP response. So the log says `Upload failed: 1:'Unsupported protocol' (cURL error)`. Please make it work correctly. Also, add expectations for onAudioClipReady, similar to: https://github.com/rdkcentral/rdkservices/pull/2390/files#diff-c89082c11121049d83b0daafa144ca170429588534bde75070e75e41e33a2093 . ShouldTurnOnAudioCapture and ShouldUploadData invoke the same APIs. Do we need both of these tests?

**Comment by mateusz-adamski-red** [comment]
> 

We have 2 tests, because there is 2 different expectations. First test check only if `enableAudioCapture` work. Second test check how events are handling. I think we should have 2 separate test. Follow rule 1 test - 1 behavior.

**Comment by npoltorapavlo** [comment]
Please remove enableAudioCapture and getAudioClip from ShouldUploadData if they are not required for eventHandler to work. Also please write expectations for all IARM_Bus_Call-s. Your test is using uninitialized values. For example, max_buffer_duration is 78250038 so the check `_max_supported_duration < incoming_duration` works by chance. constructFormatString fails because the values are uninitialized. The test should not rely on uninitialized values. Please fix.

**Comment by mateusz-adamski-red** [comment]
> Please remove enableAudioCapture and getAudioClip from ShouldUploadData if they are not required for eventHandler to work. Also please write expectations for all IARM_Bus_Call-s. Your test is using uninitialized values. For example, max_buffer_duration is 78250038 so the check `_max_supported_duration < incoming_duration` works by chance. constructFormatString fails because the values are uninitialized. The test should not rely on uninitialized values. Please fix.

Expecations added. We need  getAudioClip from ShouldUploadData in enableAudioCapture test.

**Comment by npoltorapavlo** [comment]
with your test valgrind reports:
- 8 uninitialised
- 8 Invalid read
- FILE DESCRIPTORS: 10 open at exit
- definitely lost: 480 bytes in 5 blocks

without your test, it's:
- 2 uninitialised
- no Invalid read
- FILE DESCRIPTORS: 4 open at exit
- definitely lost: 24 bytes in 2 blocks

Please fix

**Comment by npoltorapavlo** [comment]
looks good

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
