### PR TITLE
Allow mixed content

### PR DESCRIPTION
**Pull request by varumugam123**

### CODE REVIEW

**Comment by varumugam123** [comment]
@emutavchi , @goruklu Could you review this?

**Comment by varumugam123** [comment]
@HaseenaSainul Could you please review this change?

**Review by emutavchi — APPROVED** [review]
Looks good to me. Let's wait for Metro review before submitting the change

**Review by goruklu — APPROVED** [review]

**Review by modeveci — APPROVED** [review]
Looks good to me!

**Review by HaseenaSainul — APPROVED** [review]

**Pull request merged**
