### PR TITLE
RDKDEV-438: DisplayInfo: Include "tvhdrtypes" property on DisplayInfo REST API calls.

### PR DESCRIPTION
**Pull request by prajwal-tata**
The DisplayInfo.cpp file is modified to invoke TVCapabilities() which basically passes an iterator to get the HDR types supported by TV, these values are then updated against new DisplayInfo property '**tvhdrtypes**'.

### CODE REVIEW

**Comment by prajwal-tata** [comment]
Depended PR's:
https://github.com/rdkcentral/ThunderInterfaces/pull/221
https://github.com/rdkcentral/ThunderClientLibraries/pull/177

**Comment by pradeeptakdas** [comment]
Hi @prajwal-tata 
Can you please create a PR against latest dev sprint/23Q1?

**Comment by prajwal-tata** [comment]
> Hi @prajwal-tata Can you please create a PR against latest dev sprint/23Q1?

Hello @pradeeptakdas we dont have a way to test with sprint/23Q1 branch changes.

**Comment by prajwl-p** [comment]
> Hi @pradeeptakdas , as @prajwal-tata mentioned, we don't have a way to test this on the latest sprint branch, so we can't be comfortable in doing so, unless the code matches with what we're using (@prajwal-tata , can you check?).
> 
> We can only commit to the branches/revisions we're using currently. For this and similar cases, we suggest to get this merged and then RDK can cherry pick to the latest sprint and test.

Hi @rjpdasilva , checked that there is already similar changes for fetching TV HDR formats with the sprint/23Q1 branch as "tvhdrcapabilities"

> Hi @pradeeptakdas , as @prajwal-tata mentioned, we don't have a way to test this on the latest sprint branch, so we can't be comfortable in doing so, unless the code matches with what we're using (@prajwal-tata , can you check?).
> 
> We can only commit to the branches/revisions we're using currently. For this and similar cases, we suggest to get this merged and then RDK can cherry pick to the latest sprint and test.

Hi @rjpdasilva , checked with the code in sprint/23Q1 branch, could see that there is already similar code to fetch HDR of TV -> "**tvcapabilities**". So, dont think these changes are required there.

**Comment by prajwl-p** [comment]
> Hi @pradeeptakdas , as @prajwal-tata mentioned, we don't have a way to test this on the latest sprint branch, so we can't be comfortable in doing so, unless the code matches with what we're using (@prajwal-tata , can you check?).
> 
> We can only commit to the branches/revisions we're using currently. For this and similar cases, we suggest to get this merged and then RDK can cherry pick to the latest sprint and test.
yes @rjpdasilva think this could be more feasible, the changes dont exactly match.

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
