### PR TITLE
Event not triggering for Volume level 'zero'

### PR DESCRIPTION
**Pull request by arunl2910**

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket created for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4353

**Comment by anand-ky** [comment]
@apatel859,
Pls review.

**Review by apatel859 — CHANGES_REQUESTED** [review]
There is no use of cache_volumelevel variable. current implementation is wrong:

either u can make cache_volumelevel as static then it will make sense

**Comment by arunl2910** [comment]
> There is no use of cache_volumelevel variable. current implementation is wrong:
> 
> either u can make cache_volumelevel as static then it will make sense

@apatel859 as per discussion have addressed the above points, please review the changes

**Review by apatel859 — APPROVED** [review]

**Pull request merged**
