### PR TITLE
DELIA-44326 : [Thunder][Dis[laySettings] - HDMI Audio Delay Issues

### PR DESCRIPTION
**Pull request by sborushevsky**
Fixed exception handling fromp stoi call.

### CODE REVIEW

**Comment by sborushevsky** [comment]
> Please keep both the catch statements and add logging about the exception.

LOG_DEVICE_EXCEPTION1 is for device::Exception, not for std::exception.
std::exception::what() returns "stoi", which is not very descriptive about what happened, so I didn't use it.

**Comment by anand-ky** [comment]
> > Please keep both the catch statements and add logging about the exception.
> 
> LOG_DEVICE_EXCEPTION1 is for device::Exception, not for std::exception.
> std::exception::what() returns "stoi", which is not very descriptive about what happened, so I didn't use it.

ok, sounds good. As discussed, pls make similar change in other places where stoi is used.

**Comment by sborushevsky** [comment]
> > > Please keep both the catch statements and add logging about the exception.
> > 
> > 
> > LOG_DEVICE_EXCEPTION1 is for device::Exception, not for std::exception.
> > std::exception::what() returns "stoi", which is not very descriptive about what happened, so I didn't use it.
> 
> ok, sounds good. As discussed, pls make similar change in other places where stoi is used.

Created https://github.com/rdkcentral/rdkservices/pull/123 for the rest of stoi calls.

**Comment by vijs** [comment]
Merged https://github.com/rdkcentral/rdkservices/pull/124

**Pull request closed without merging**
