### PR TITLE
WebKitBrowser json and md file Updated as per code

### PR DESCRIPTION
**Pull request by svenka471**
Documentation Enhancement For WebKitBrowser Plugin 

jira : https://ccp.sys.comcast.net/browse/RDK-35061

### CODE REVIEW

**Comment by emutavchi** [comment]
Change looks good to me. @HaseenaSainul @MFransen69  could you please take a look a well?

On a side note, WebKitBrowser.json gets overridden on every configuration. Not sure when it was added. Maybe it could be moved to a doc folder. @jruzzi is this something you could work on?

**Comment by emutavchi** [comment]
@svenka471 please create PR to 2201 sprint first. The change would have to be cherry-picked to main after RM approval

**Comment by HaseenaSainul** [comment]
I see all the rdkservces plugins contain <plugin>.json in the plugin folder, which is overridden on configuration time

**Review by MFransen69 — APPROVED** [review]

**Review by HaseenaSainul — APPROVED** [review]

**Comment by HaseenaSainul** [comment]
@emutavchi , it seems fine for me. But would like to add Ozgur also in the review list. Currently I am not able to select.

**Comment by svenka471** [comment]
> @svenka471 please create PR to 2201 sprint first. The change would have to be cherry-picked to main after RM approval

PR created to 2201 sprint : https://github.com/rdkcentral/rdkservices/pull/2127

**Comment by anand-ky** [comment]
@svenka471 - Is this good to be merged to main?

**Comment by anand-ky** [comment]
Changes already merged to main. Closing PR.

**Pull request closed without merging**
