### PR TITLE
RDKTV-231: System setCachedValue and removeCacheKey fix

### PR DESCRIPTION
**Pull request by arun-madhavan-013**
- System plugin sync up from Sprint2009 to sprint2010
- Fix for RDKTV-231 & RDKTV-230: System setCachedValue and removeCacheKey fix

### CODE REVIEW

**Review by anand-ky — APPROVED** [review]
looks good.

**Review by vijs — CHANGES_REQUESTED** [review]
Please don't make any changes to COPYING file

**Comment by arun-madhavan-013** [comment]
> Please don't make any changes to COPYING file
I took this COPYING from sprint/2009. Replaced COPYING file with that of main branch as suggested.

**Comment by arun-madhavan-013** [comment]
> Please don't make any changes to COPYING file
I took this COPYING from sprint/2009. Replaced COPYING file with that of main branch as suggested.

**Comment by arun-madhavan-013** [comment]
@vijs , could you please review this.
Thanks

**Review by vijs — APPROVED** [review]

**Pull request merged**
