### PR TITLE
RDK-32142: UsbAccess plugin update per spec

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Reason for change: Add "success":false case.
Test Procedure: For API getMounted, getAvailableFirmwareFiles.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Nikita,
The code at 270-295 is matching closely to an OSS project.  Where does this code come from?
Thanks,
Martin

**Comment by npoltorapavlo** [comment]
Martin, this is a typical code to iterate USB devices. It doesn't come from anywhere.

**Comment by mhughesacn** [comment]
Thanks Nikita: So please confirm that this is code independently written by you, and any resemblance to external code (including variable names) is coincidence.  If this is the case, I will approve.

**Comment by npoltorapavlo** [comment]
confirming. Please approve

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
