### PR TITLE
RDKDEV-993 : Adding Realtek PlatformImplementation for DisplayInfo plugin

### PR DESCRIPTION
**Pull request by liginPunoose**
Reason for change: Adding Realtek PlatformImplementation for DisplayInfo plugin

Test Procedure: Build and verify

Risks: Low

Signed-off-by: Ligin Abraham Punoose <ligin_punoose@comcast.com>

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4635

**Comment by anand-ky** [comment]
@liginPunoose - Pls add ticket details

**Comment by liginPunoose** [comment]
@anand-ky https://jira.rdkcentral.com/jira/browse/RDKDEV-993

**Comment by viveksinghnarwaria** [comment]
Hi @liginPunoose 
The latest sprint branch is 24Q2_sprint. so please migrate the changes to the latest sprint branch,

**Pull request closed without merging**
