### PR TITLE
RDKTV-13125: WPEFramework timeout during shutdown

### PR DESCRIPTION
**Pull request by livinsunny519**
Reason for change:Due to maintenance running the task seems to be
blocked.
Test Procedure:Refer Ticket.
Risks: Low

(cherry picked from commit b8154719a21bcd3f4a64766edd93eaf4b65d81f3)

### CODE REVIEW

**Comment by livinsunny519** [comment]
Do not merge. Dev Testing in progress.

**Comment by mhughesacn** [comment]
Hi Livinsunny,
Github has a problem with the CLA status.  This is external to RDK - we don't have control of the check.  There are a few workarounds but the easiest may be to update the commit with an extra comment or other neutral change and see if it gets processed properly.  So when you are ready to merge, please try this first.  If it doesn't work, please report back (Comcast slack may be best).  I am not fully back from vacation until next week so it may take a little longer to sync with you.
Thank you,
Martin Hughes, RDK CMF Compliance Team

**Comment by Firdose2109** [comment]
Can one of the admins verify this patch?

**Comment by anand-ky** [comment]
Closing older PRs. Pls resubmit to latest 2205 sprint.

**Pull request closed without merging**
