### PR TITLE
WebKitBrowser: Amazon: Allow configuring width and height

### PR DESCRIPTION
**Pull request by rjpdasilva**
Add the new 'PLUGIN_AMAZON_WIDTH' and 'PLUGIN_AMAZON_HEIGHT' cmake
variables to allow externally configuring the width/height used by the
Amazon's WebKitBrowser instance.

This is needed to take advantage of the new Amazon Prime Video UI, now supporting 1920x1080 resolution.

Keep the defaults of 1280x720 for backwards compatibility.

### CODE REVIEW

**Comment by rjpdasilva** [comment]
@pwielders, can this be reviewed please?

**Review by pwielders — APPROVED** [review]

**Comment by pwielders** [comment]
@vijs / @anand-ky this is just an additional setting for amazon (hybrid) from a Metrological customer for his project. It does not cause any regression.

**Comment by anand-ky** [comment]
@emutavchi - Pls review.

**Comment by rjpdasilva** [comment]
@pwielders, @anand-ky, @emutavchi, how can we follow up on this PR to get it merged?

**Review by emutavchi — APPROVED** [review]

**Comment by anand-ky** [comment]
@rjpdasilva - Change has been cherry-picked to 2107 branch. Please add ticket details, get this tested and go thru release process so that we can bring it to main (stable2) branch.

**Comment by rjpdasilva** [comment]
@anand-ky,

> @rjpdasilva - Change has been cherry-picked to 2107 branch. Please add ticket details, get this tested and go thru release process so that we can bring it to main (stable2) branch.

Not something I can do, we're only using the 2101 branch and have no way to test this on other branches, that's why we've opened this PR to the 2101 branch.
Let me know if I can help otherwise.

**Pull request merged**
