### PR TITLE
DELIA-58191 : Use interfaces instead of JSON-RPC

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Reason for change: Fix design flaws.

Test Procedure: Check for logs:
"no IStore" or "IStore status",
"no IShell" or "IShell config" / "IShell state" /
/ "IShell activate status" / "IShell deactivate status.

Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
link to successful gerrit verification https://gerrit.teamccp.com/#/c/683352/
ZWCN11MWI_VBN_22Q4_sprint_20220930154402sdy_TEST

plui loads
logs
```
root@platco-cad15:~# grep 'IStore\|IShell' /opt/logs/wpeframework.log*
2022 Sep 30 16:53:01.494701 WPEFramework[6644]:  IStore status 1 for get AgingState
2022 Sep 30 16:53:01.505734 WPEFramework[6644]:  IStore status 0 for get FactoryMode
2022 Sep 30 16:53:03.211456 WPEFramework[6644]:  IStore status 1 for get AgingState
2022 Sep 30 16:53:03.212678 WPEFramework[6644]:  IStore status 0 for get FactoryMode
2022 Sep 30 16:53:25.679465 WPEFramework[6644]:  IShell config {
2022 Sep 30 16:53:25.725047 WPEFramework[6644]:  IShell config status 0 for SearchAndDiscovery
2022 Sep 30 16:53:26.725110 WPEFramework[6644]:  IShell activate status 0 for SearchAndDiscovery
2022 Sep 30 16:56:50.153036 WPEFramework[6644]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"aa","inspector":":::10003","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:2m,video:15m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"noncompositedwebgl":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache","height":720,"width":1280,"clientidentifier":"SearchAndDiscoveryApp\/wst-SearchAndDiscovery","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","localstoragesize":5120,"cookiestorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":false,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"root":{"mode":"Local","locator":"libWPEFrameworkWebKitBrowserImpl.so","outofprocess":true},"language":"en-US"} for SearchAndDiscovery
2022 Sep 30 16:56:50.158093 WPEFramework[6644]:  IShell config status 5 for SearchAndDiscovery
2022 Sep 30 16:56:50.159242 WPEFramework[6644]:  IShell config status 5 for SearchAndDiscovery
2022 Sep 30 16:56:50.159958 WPEFramework[6644]:  IShell state 3 for SearchAndDiscovery
2022 Sep 30 16:56:57.924274 WPEFramework[6644]:  IShell config {
2022 Sep 30 16:56:57.954797 WPEFramework[6644]:  IShell config status 0 for Netflix-0
2022 Sep 30 16:57:00.439386 WPEFramework[6644]:  IShell activate status 0 for Netflix-0
2022 Sep 30 16:57:03.807051 WPEFramework[6644]:  IShell config {
2022 Sep 30 16:57:03.850610 WPEFramework[6644]:  IShell config status 0 for Cobalt-0
2022 Sep 30 16:57:05.409117 WPEFramework[6644]:  IShell activate status 0 for Cobalt-0
2022 Sep 30 16:57:05.679512 WPEFramework[6644]:  IShell config {
2022 Sep 30 16:57:05.721832 WPEFramework[6644]:  IShell config status 0 for HtmlApp-0
2022 Sep 30 16:57:07.509686 WPEFramework[6644]:  IShell activate status 0 for HtmlApp-0
```

**Comment by anand-ky** [comment]
@binuinbaraj - Pls review RDKShell changes.

**Comment by npoltorapavlo** [comment]
ZWCN11MWI_VBN_22Q4_sprint_20221003110025sdy_GRT

plui loads
logs
```
root@platco-cad15:~# grep 'IStore\|IShell\|IController' /opt/logs/wpeframework.log*
/opt/logs/wpeframework.log:2022 Oct 03 12:16:49.204558 WPEFramework[6608]:  IShell state 1 for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:49.204992 WPEFramework[6608]:  IShell state 1 for Netflix
/opt/logs/wpeframework.log:2022 Oct 03 12:16:49.205429 WPEFramework[6608]:  IShell config {"silent":false,"suspendtimeout":12000,"resumetimeout":8000,"fullhd":true,"keyrepeatdelay":10,"clientidentifier":"Netflix\/wst-Netflix-0","audiocodecs":"aac,ddp2.0,ddp5.1","videocodecs":"avc-main,avc-high","vaultpath":"\/opt\/drm\/netflix\/manuf_ss.bin","postfix":"dev","videobuffersize":115343360,"audiobuffersize":2621440,"surfacecache":29360128,"diskcache":31457280,"writedatapath":"\/opt\/netflix","console":true,"idfile":"\/opt\/drm\/netflix\/manuf_ss.bin","language":"en-US","querystring":"source_type=22&iid=ee4255bf","defaultworkingdirectory":"\/usr\/share\/netflix\/bin","ramworkingdirectory":"\/tmp\/netflix\/usr\/share\/netflix\/bin","sdcardworkingdirectory":"\/media\/apps\/netflix\/usr\/share\/netflix\/bin","dnsfallbackservers":"2001:4860:4860::8888","prioritytimeout":30,"mediacache":249561088,"enable1080p":true,"enableflexiblegraphicsmem":true,"playreadystoragedir":"\/opt\/netflix\/dpi\/playready\/storage","drmdir":"\/opt\/drm\/netflix","netflixversion":"5.3.1","backtracemaxframes":64,"root":{"mode":"Container","priority":10},"mdx":true,"mdxinterface":"eth0:0","launchtosuspend":true} for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:49.228137 WPEFramework[6608]:  IShell config status 0 for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:49.228943 WPEFramework[6608]:  IShell state 1 for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:50.438161 WPEFramework[6608]:  IShell activate status 1 for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.186466 WPEFramework[6608]:  IShell activate status 1 for Netflix-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.236986 WPEFramework[6608]:  IShell state 1 for Cobalt-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.237458 WPEFramework[6608]:  IShell state 1 for Cobalt
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.237903 WPEFramework[6608]:  IShell config {"url":"https:\/\/www.youtube.com\/tv?launch=preload&lmt=0&us_privacy=1-N-&inApp=false","clientidentifier":"Cobalt\/wst-Cobalt-0","closurepolicy":"suspend","systemproperties":{
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.285889 WPEFramework[6608]:  IShell config status 0 for Cobalt-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:52.286733 WPEFramework[6608]:  IShell state 1 for Cobalt-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:53.769733 WPEFramework[6608]:  IShell activate status 1 for Cobalt-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.236762 WPEFramework[6608]:  IShell activate status 1 for Cobalt-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.313352 WPEFramework[6608]:  IShell state 1 for HtmlApp-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.313749 WPEFramework[6608]:  IShell state 1 for HtmlApp
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.314520 WPEFramework[6608]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"noaa","inspector":":::10001","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:6m,video:90m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache\/HtmlApp","height":720,"width":1280,"clientidentifier":"HtmlApp\/wst-HtmlApp-0","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/HtmlApp","localstoragesize":100,"cookiestorage":"\/opt\/persistent\/rdkservices\/HtmlApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":true,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"loadblankpageonsuspendenabled":true,"root":{"mode":"Container","locator":"libWPEFrameworkWebKitBrowserImpl.so"},"language":"en-US"} for HtmlApp-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.321533 WPEFramework[6608]:  IShell config status 0 for HtmlApp-0
/opt/logs/wpeframework.log:2022 Oct 03 12:16:55.322214 WPEFramework[6608]:  IShell state 1 for HtmlApp-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:41.067189 WPEFramework[6608]:  IStore status 1 for get AgingState
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:41.068239 WPEFramework[6608]:  IStore status 0 for get FactoryMode
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:42.724022 WPEFramework[6608]:  IStore status 1 for get AgingState
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:42.732814 WPEFramework[6608]:  IStore status 0 for get FactoryMode
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:49.771219 WPEFramework[6608]:  no IShell for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:49.771804 WPEFramework[6608]:  IShell state 1 for SearchAndDiscoveryApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:49.773069 WPEFramework[6608]:  IController clone status 0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:50.078418 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:50.139641 WPEFramework[6608]:  IShell config status 0 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:50.754497 WPEFramework[6608]:  IShell activate status 0 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:51.457163 WPEFramework[6608]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"aa","inspector":":::10003","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:2m,video:15m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"noncompositedwebgl":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache","height":720,"width":1280,"clientidentifier":"SearchAndDiscoveryApp\/wst-SearchAndDiscovery","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","localstoragesize":5120,"cookiestorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":false,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"root":{"mode":"Local","locator":"libWPEFrameworkWebKitBrowserImpl.so","outofprocess":true},"language":"en-US"} for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:51.489757 WPEFramework[6608]:  IShell config status 5 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:51.490757 WPEFramework[6608]:  IShell config status 5 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:12:51.491398 WPEFramework[6608]:  IShell state 3 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:22.422676 WPEFramework[6608]:  no IShell for Netflix-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:22.423230 WPEFramework[6608]:  IShell state 1 for Netflix
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:22.429558 WPEFramework[6608]:  IController clone status 0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:22.515484 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:22.569644 WPEFramework[6608]:  IShell config status 0 for Netflix-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:24.851796 WPEFramework[6608]:  IShell activate status 0 for Netflix-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:27.124971 WPEFramework[6608]:  no IShell for Cobalt-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:27.125464 WPEFramework[6608]:  IShell state 1 for Cobalt
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:27.131873 WPEFramework[6608]:  IController clone status 0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:27.235229 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:27.241709 WPEFramework[6608]:  IShell config status 0 for Cobalt-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.263639 WPEFramework[6608]:  IShell activate status 0 for Cobalt-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.353130 WPEFramework[6608]:  no IShell for HtmlApp-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.353540 WPEFramework[6608]:  IShell state 1 for HtmlApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.354263 WPEFramework[6608]:  IController clone status 0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.440882 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:28.458714 WPEFramework[6608]:  IShell config status 0 for HtmlApp-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:14:29.908438 WPEFramework[6608]:  IShell activate status 0 for HtmlApp-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:20.473538 WPEFramework[6608]:  IShell deactivate status 0 for Cobalt-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:21.203844 WPEFramework[6608]:  IShell deactivate status 0 for HtmlApp-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:21.204684 WPEFramework[6608]:  IShell deactivate status 0 for Cobalt-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.386387 WPEFramework[6608]:  IShell deactivate status 0 for Netflix-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.387919 WPEFramework[6608]:  IShell deactivate status 0 for Netflix-0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.487227 WPEFramework[6608]:  IShell deactivate status 0 for ResidentApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.586974 WPEFramework[6608]:  IShell deactivate status 0 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.591299 WPEFramework[6608]:  IShell deactivate status 0 for ResidentApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.593315 WPEFramework[6608]:  no IShell for factoryapp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.593655 WPEFramework[6608]:  IShell state 1 for ResidentApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.594582 WPEFramework[6608]:  IController clone status 0
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.655336 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:22.687903 WPEFramework[6608]:  IShell config status 0 for factoryapp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:23.015445 WPEFramework[6608]:  IShell activate status 0 for factoryapp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:23.084810 WPEFramework[6608]:  IStore status 0 for set FactoryMode
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:23.091901 WPEFramework[6608]:  IStore status 0 for set AllowExit
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:34.223533 WPEFramework[6608]:  IStore status 1 for get AgingState
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:34.225007 WPEFramework[6608]:  IStore status 0 for get AllowExit
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:35.486368 WPEFramework[6608]:  IShell deactivate status 0 for factoryapp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:35.489110 WPEFramework[6608]:  IShell deactivate status 0 for factoryapp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:35.492840 WPEFramework[6608]:  IShell config {
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:35.806989 WPEFramework[6608]:  IShell activate status 0 for ResidentApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:35.821252 WPEFramework[6608]:  IStore status 0 for set FactoryMode
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.323004 WPEFramework[6608]:  IShell state 1 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.323468 WPEFramework[6608]:  IShell state 1 for SearchAndDiscoveryApp
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.323926 WPEFramework[6608]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"aa","inspector":":::10003","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:2m,video:15m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"noncompositedwebgl":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache","height":720,"width":1280,"clientidentifier":"SearchAndDiscoveryApp\/wst-SearchAndDiscovery","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","localstoragesize":5120,"cookiestorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":false,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"root":{"mode":"Local","locator":"libWPEFrameworkWebKitBrowserImpl.so","outofprocess":true},"language":"en-US"} for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.332809 WPEFramework[6608]:  IShell config status 0 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.333648 WPEFramework[6608]:  IShell state 1 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:39.788101 WPEFramework[6608]:  IShell activate status 0 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:40.425156 WPEFramework[6608]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"aa","inspector":":::10003","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:2m,video:15m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"noncompositedwebgl":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache","height":720,"width":1280,"clientidentifier":"SearchAndDiscoveryApp\/wst-SearchAndDiscovery","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","localstoragesize":5120,"cookiestorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":false,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"root":{"mode":"Local","locator":"libWPEFrameworkWebKitBrowserImpl.so","outofprocess":true},"language":"en-US"} for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:40.427251 WPEFramework[6608]:  IShell config status 5 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:40.428298 WPEFramework[6608]:  IShell config status 5 for SearchAndDiscovery
/opt/logs/wpeframework.log.1:2022 Oct 03 12:16:40.428987 WPEFramework[6608]:  IShell state 3 for SearchAndDiscovery
```

**Comment by npoltorapavlo** [comment]
fyi, observing ENT-37036 when trying to open Youtube app. Will check and update

**Review by binuinbaraj — APPROVED** [review]

**Comment by npoltorapavlo** [comment]
retested youtube, no ENT-37036
ZWCN11MWI_VBN_22Q4_sprint_20221004130822sdy_GRT

logs
```
root@platco-cad15:~# grep 'IStore\|IShell\|IController' /opt/logs/wpeframework.log*
2022 Oct 04 14:37:32.385390 WPEFramework[6600]:  IStore status 1 for get AgingState
2022 Oct 04 14:37:32.393243 WPEFramework[6600]:  IStore status 0 for get FactoryMode
2022 Oct 04 14:37:34.670998 WPEFramework[6600]:  IStore status 1 for get AgingState
2022 Oct 04 14:37:34.672203 WPEFramework[6600]:  IStore status 0 for get FactoryMode
2022 Oct 04 14:37:39.786235 WPEFramework[6600]:  no IShell for SearchAndDiscovery
2022 Oct 04 14:37:39.787338 WPEFramework[6600]:  IShell state 1 for SearchAndDiscoveryApp
2022 Oct 04 14:37:39.791591 WPEFramework[6600]:  IController clone status 0
2022 Oct 04 14:37:39.999399 WPEFramework[6600]:  IShell config {
2022 Oct 04 14:37:40.036663 WPEFramework[6600]:  IShell config status 0 for SearchAndDiscovery
2022 Oct 04 14:37:40.450953 WPEFramework[6600]:  IShell activate status 0 for SearchAndDiscovery
2022 Oct 04 14:39:05.666646 WPEFramework[6600]:  IShell config {"url":"about:blank","extensiondir":"Extension","transparent":true,"compositor":"aa","inspector":":::10003","fps":true,"cursor":false,"touch":false,"msebuffers":"audio:2m,video:15m,text:1m","memoryprofile":"1024m","memorypressure":"databaseprocess:50m,networkprocess:50m,webprocess:512m,rpcprocess:50m","mediadiskcache":false,"diskcache":"64m","xhrcache":true,"noncompositedwebgl":true,"webgl":true,"threadedpainting":1,"diskcachedir":"\/media\/apps\/.cache","height":720,"width":1280,"clientidentifier":"SearchAndDiscoveryApp\/wst-SearchAndDiscovery","localstorageenabled":false,"localstorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","localstoragesize":5120,"cookiestorage":"\/opt\/persistent\/rdkservices\/SearchAndDiscoveryApp","clientcert":"\/etc\/rdkbrowser2\/ottapps.xcal.tv.cert.pem","clientcertkey":"\/tmp\/.rdkbrowser2_init\/.yreguglpgpmd.socket","secure":false,"watchdogchecktimeoutinseconds":10,"watchdoghangthresholdtinseconds":60,"root":{"mode":"Local","locator":"libWPEFrameworkWebKitBrowserImpl.so","outofprocess":true},"language":"en-US"} for SearchAndDiscovery
2022 Oct 04 14:39:05.671557 WPEFramework[6600]:  IShell config status 5 for SearchAndDiscovery
2022 Oct 04 14:39:05.672629 WPEFramework[6600]:  IShell config status 5 for SearchAndDiscovery
2022 Oct 04 14:39:05.673291 WPEFramework[6600]:  IShell state 3 for SearchAndDiscovery
2022 Oct 04 14:39:12.930527 WPEFramework[6600]:  no IShell for Netflix-0
2022 Oct 04 14:39:12.931056 WPEFramework[6600]:  IShell state 1 for Netflix
2022 Oct 04 14:39:12.932589 WPEFramework[6600]:  IController clone status 0
2022 Oct 04 14:39:12.995301 WPEFramework[6600]:  IShell config {
2022 Oct 04 14:39:13.037764 WPEFramework[6600]:  IShell config status 0 for Netflix-0
2022 Oct 04 14:39:14.745025 WPEFramework[6600]:  IShell activate status 0 for Netflix-0
2022 Oct 04 14:39:17.160217 WPEFramework[6600]:  no IShell for Cobalt-0
2022 Oct 04 14:39:17.160661 WPEFramework[6600]:  IShell state 1 for Cobalt
2022 Oct 04 14:39:17.161594 WPEFramework[6600]:  IController clone status 0
2022 Oct 04 14:39:17.271450 WPEFramework[6600]:  IShell config {
2022 Oct 04 14:39:17.305801 WPEFramework[6600]:  IShell config status 0 for Cobalt-0
2022 Oct 04 14:39:18.790358 WPEFramework[6600]:  IShell activate status 0 for Cobalt-0
2022 Oct 04 14:39:18.857557 WPEFramework[6600]:  no IShell for HtmlApp-0
2022 Oct 04 14:39:18.858320 WPEFramework[6600]:  IShell state 1 for HtmlApp
2022 Oct 04 14:39:18.866483 WPEFramework[6600]:  IController clone status 0
2022 Oct 04 14:39:18.933128 WPEFramework[6600]:  IShell config {
2022 Oct 04 14:39:18.990948 WPEFramework[6600]:  IShell config status 0 for HtmlApp-0
2022 Oct 04 14:39:20.433571 WPEFramework[6600]:  IShell activate status 0 for HtmlApp-0
2022 Oct 04 14:39:24.248176 WPEFramework[6600]:  IShell config {"url":"https:\/\/www.youtube.com\/tv?launch=preload&lmt=0&us_privacy=1-N-&inApp=false","clientidentifier":"Cobalt\/wst-Cobalt-0","closurepolicy":"suspend","systemproperties":{
2022 Oct 04 14:39:24.258054 WPEFramework[6600]:  IShell config status 5 for Cobalt-0
2022 Oct 04 14:39:24.259345 WPEFramework[6600]:  IShell config status 5 for Cobalt-0
2022 Oct 04 14:39:24.260128 WPEFramework[6600]:  IShell state 3 for Cobalt-0
```

**Comment by npoltorapavlo** [comment]
I had intermittent issues with activate/deactivate/clone so reverted them from this changeset. The remaining changes should be safe to merge.

**Review by anand-ky — APPROVED** [review]

**Pull request merged**
