### PR TITLE
RDKTV-22508:HDMI AVI Content type Signalling for Film Maker Mode

### PR DESCRIPTION
**Pull request by aishwariya15**
Reason for change: Added the events for sending thew content type in HdmiInput Thunder plugin.
Test Procedure: Build and Verify.
Risks: Low
Signed-off-by: Aishwariya B <aishwariya.bhaskar@sky.uk>

### CODE REVIEW

**Review by apatel859 — CHANGES_REQUESTED** [review]
Update json documentation for this new event

**Comment by aishwariya15** [comment]
> Update json documentation for this new event
Updated json documentation and HdmiInputPlugin.md document

**Review by apatel859 — APPROVED** [review]

**Review by apatel859 — CHANGES_REQUESTED** [review]
could you fix the unit test error?

**Comment by aishwariya15** [comment]
Closing this as duplicate and old PR

**Pull request closed without merging**
