### PR TITLE
Add option to configure 'persistentpathpostfix'

### PR DESCRIPTION
**Pull request by emutavchi**
Requires on https://github.com/rdkcentral/Thunder/pull/603

### CODE REVIEW

**Comment by HaseenaSainul** [comment]
@emutavchi, Could you please define the PLUGIN_XXXX_PERSISTENTPATHPOSTFIX in CMakeList also with default value  as like other variables we used ?

**Review by HaseenaSainul — COMMENTED** [review]
@emutavchi, Could you please define the PLUGIN_XXXX_PERSISTENTPATHPOSTFIX in CMakeList also with default value as like other variables we used ?

**Review by MFransen69 — APPROVED** [review]

**Comment by emutavchi** [comment]
> @emutavchi, Could you please define the PLUGIN_XXXX_PERSISTENTPATHPOSTFIX in CMakeList also with default value (empty string) as like other variables we used ?

Done, please review

**Review by HaseenaSainul — APPROVED** [review]
LGTM

**Pull request merged**
