### PR TITLE
RDKCOM-3132: Upstream securityagent patches

### PR DESCRIPTION
**Pull request by npoltorapavlo**

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
https://gerrit.teamccp.com/#/c/690658/

**Comment by anand-ky** [comment]
@emutavchi - Pls review changes in WebKitBrowser.

**Comment by emutavchi** [comment]
Browser changes looks good to me. I guess similar must be done for Netflix and Cobalt.

@MFransen69  could you please review browser changes as well?

**Comment by MFransen69** [comment]
> Browser changes looks good to me. I guess similar must be done for Netflix and Cobalt.
> 
> @MFransen69 could you please review browser changes as well?

I reassigned it to Pierre he did most of the work on the security agent in the past and I'll ask him to have a look

**Comment by npoltorapavlo** [comment]
@pwielders please review

**Review by anand-ky — APPROVED** [review]

**Comment by anand-ky** [comment]
Approving it to meet sprint deadlines.

**Pull request merged**
