### PR TITLE
SGMM393-181 : Upstream Return-exact-power-states Change

### PR DESCRIPTION
**Pull request by HarshiniRavichandran**
This change is for "onSystemPowerStateChanged" event is not getting triggered for ON state

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket created for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4702

**Comment by viveksinghnarwaria** [comment]
Hi @HarshiniRavichandran , Please sign the CLA.

**Comment by viveksinghnarwaria** [comment]
Hi Harshini , 
1. Why there is another ticket change [RDKVREFPLT-721](https://github.com/rdkcentral/rdkservices/pull/5155/commits/db8caa6df5cfd7b7fb21925b16db50c258b5b0ff).
2. How is it related to SGMM393-181 ?

Please do not merge two different issues in One Pull Request. We need separate branch and pull request for each issue.

**Comment by HarshiniRavichandran** [comment]
Hi @viveksinghnarwaria 
Apologies for the oversight. I've removed the unrelated change from the pull request.I'll ensure each issue has its own separate branch and pull request. Thank you for your understanding.

**Comment by HarshiniRavichandran** [comment]
Hi All 
I regret to inform you that the repository was accidentally deleted. My sincere apologies for any inconvenience this may cause.

To rectify the situation, I've created a new pull request with the necessary changes. 
https://github.com/rdkcentral/rdkservices/pull/5201

**Pull request closed without merging**
