### PR TITLE
RDK-48800: Add pressure settings for service worker process

### PR DESCRIPTION
**Pull request by filipe-norte-red**
Depends on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1340

### CODE REVIEW

**Comment by filipe-norte-red** [comment]
Note: l1-tests are unrelated with these changes and are failing as well for other pull requests (e.g. https://github.com/rdkcentral/rdkservices/pull/5314 )

**Review by emutavchi — APPROVED** [review]

**Review by modeveci — APPROVED** [review]
LGTM

**Comment by filipe-norte-red** [comment]
@modeveci / @MFransen69 , can you kindly help merging these changes considering review & test pass, please? Thank you

**Comment by MFransen69** [comment]
Hi @filipe-norte-red 

I certainly cannot merge this PR, I will verify with Ozgur if he can do it but I think it needs to be done by the RDKServices team.

**Pull request merged**
