### PR TITLE
Rdk 33853 network and wi fi manager thunder plugin documentation

### PR DESCRIPTION
**Pull request by vgarg931**
Documentation enhancement for WifiManager Plugin and Network Plugin

### CODE REVIEW

**Comment by karuna2git** [comment]
changes approved. I see a conflict. Please resolve and bring the changes to main branch as well.

**Comment by karuna2git** [comment]
changes approved. I see a conflict. Please resolve and bring the changes to main branch as well.

**Comment by Firdose2109** [comment]
Can one of the admins verify this patch?

**Comment by anand-ky** [comment]
Closing older PRs. Pls resubmit to latest 2205 sprint.

**Pull request closed without merging**
