### PR TITLE
RDK-38406: Startupscreen launch failed with webkitbrowserplugin backend

### PR DESCRIPTION
**Pull request by varumugam123**
Reason for change: On startup screen launch the "Internet" precondition is not met for HtmlApp callsign. This precondition is not required for HtmlApp & LightningApp callsigns as it might be possible for launching locally hosted pages with those callsigns
Test Procedure: Verify startupscreen is loaded with webkitbrowserplugin Priority: P1
Risks: None

Signed-off-by: Vivek.A <vivek_arumugam@comcast.com>

### CODE REVIEW

**Review by emutavchi — APPROVED** [review]
Approving. Based on the use cases where we need to use these callsigns in offline mode as well.

**Comment by emutavchi** [comment]
@modeveci need a formal +1 from you. Could you please take a look?

**Comment by varumugam123** [comment]
Hi @modeveci, could you review this?

**Review by modeveci — APPROVED** [review]
LGTM

**Pull request merged**
