### PR TITLE
RDKDEV-991 - Add additional methods in UsbAccess plugin

### PR DESCRIPTION
**Pull request by jithajamesp**
Reason for change: unmountUSB, getUSBSize, getFileInfo, getMountedInfo, getPartitionInfo, getPartitionCount, getDeviceCount methods added in UsbAccess plugin

Risks: Low

Test Procedure: Use curl commands and verify all the commands give proper responses

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Hi @jithajamesp 

Please sign the CLA

**Comment by pradeeptakdas** [comment]
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4634

**Comment by viveksinghnarwaria** [comment]
Please bring the changes to 24Q2_sprint branch .

**Comment by jithajamesp** [comment]
Create pull request in 24q2 sprint branch: https://github.com/rdkcentral/rdkservices/pull/5144

**Pull request closed without merging**
