### PR TITLE
DELIA-46582 : Cherrypick Infoplugins to sprint/2010

### PR DESCRIPTION
**Pull request by vinod-jacob**
Reason for change: Cherrypick Infoplugins from
sprint/2009 to sprint/2010
Test Procedure:Check Ticket
Risks: None
Signed-off-by: Vinod Jacob vinod_jacob@comcast.com

### CODE REVIEW

**Comment by vinod-jacob** [comment]
@anooja-ku, could you please review the cherry-picked changes from sprint/2009 to sprint/2010.

**Comment by anooja-ku** [comment]
looks okay

**Comment by vinod-jacob** [comment]
Wasn't able to create a Jenkins image with these changes as Thunder revision on 2010_sprint is still pointing to `

# R1 08/19/2020
--
  | SRCREV = "53a4e35904641391dc5d04afa7b147c4fbd79706"

`
Trying to generate a build by manually updating the Thunder revision to the latest as per rdkcentral/Thunder is causing build errors in other plugins, as they will need to be cherry-picked to 2010 sprint as well

**Comment by vinod-jacob** [comment]
These changes have been added in the PR
https://github.com/rdkcentral/rdkservices/pull/409

**Pull request closed without merging**
