### PR TITLE
[OCDM] Enhancements

### PR DESCRIPTION
**Pull request by kkanag314**
1. Support passing Encryption Scheme and Pattern to Decrypt
     2. New Gstreamer Adapter method that parses Sample and Subsample info
        from GstStructure in ProitectionMetdata of GstBuffer
     3. New gstreamer adapter API supports passing Subsample Info to the DRM
        implementation without processing it.

Backporting the commit from R2 branch https://github.com/rdkcentral/rdkservices/commit/5ee2371448d41050199684ed2f1eeb181f758747

### CODE REVIEW

**Comment by kkanag314** [comment]
@anand-ky Could you please review the changes

**Comment by anand-ky** [comment]
@kkanag314 - Pls add details on the ticket. Does this need thunder or other dependencies? Pls make sure they are merged to sprint first.

**Comment by pwielders** [comment]
Uhhh to keep the upstream work aligned with these major change, can we share what is driving this change? Is there a document describing the PSSH parsing of thew widevine box, now done with an external Protobuf.h file ?

**Comment by anand-ky** [comment]
Closing older PRs. Pls create new PRs on latest sprint branch.

**Pull request closed without merging**
