### PR TITLE
Monitor: Syncup with Metro plugin changes

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Review by MFransen69 — APPROVED** [review]

**Comment by anand-ky** [comment]
@emutavchi - Pls review.

**Review by emutavchi — APPROVED** [review]
@anand-ky  looks good to me.

**Comment by anand-ky** [comment]
@HaseenaSainul - Pls add the Metro ticket details.

**Comment by HaseenaSainul** [comment]
> @HaseenaSainul - Pls add the Metro ticket details.

PR name updated with ticket number

**Comment by pradeeptakdas** [comment]
Internal JIRA for tracking https://ccp.sys.comcast.net/browse/RDKCOM-2910

**Pull request merged**
