### PR TITLE
 RDK-28817: Packager + DAC functionality 

### PR DESCRIPTION
**Pull request by FitzerIRL**
NOTE: This PR depends on  [Thunder PR 323](https://github.com/rdkcentral/Thunder/pull/323) for interface changes.

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Fitzer,
Sorry for the delay but this has been a complicated scan.  I work in the RDK CMF Compliance Team.  I scanned the PR as of some hours ago but the relevant parts have not changed, as far as I can see.

There are a number of compliance issues with this pull req:

1.
Where do the image files come from?  If they are not original, how are they licensed?
One image is credited in the readme to https://commons.wikimedia.org/wiki/File:Eo_circle_light-green_white_checkmark.svg
which is licensed as Creative Commons Attribution-Share Alike 4.0 International (not currently approved and no automatic guarantee of approval.)  Trash Can.svg is matching in the scan tool.  It is public domain (Clip Art) and probably OK but I will have to request permission.
So please list all the image files and their source, so we can see what is required.  Please be aware that approval or rejection of a new license can take several days.

2.
Header missing from several files in this directory and below:
Packager/test/demo/com.comcast.pkgDemo/src/components/

3.
Please add the following to NOTICE:

Roboto Regular font is:
Copyright 2017 Google Inc. All Rights Reserved.
Licensed under the Apache License, Version 2.0

4.
Packager/PackagerExUtils.cpp
Two code matches here:
(i) A match to libarchive code.
PackagerExUtils_1
Probably a reasonable source at https://valadoc.org/libarchive/Archive.Read.html which is licensed the same as the source i.e. BSD-2 according to: https://raw.githubusercontent.com/libarchive/libarchive/master/COPYING.  This should be credited, so in the source file round 970, add:

Copyright (c) 2003-2018 Tim Kientzle
Licensed under the BSD-2 License

and in NOTICE, please append the same two lines
and in LICENSE, no change because there is already a copy of the BSD-2 license there.

(ii) The pxCore match (which was partially credited but removed): please add back before line 319:

Based on pxCore, Copyright 2015-2018 John Robinson
Licensed under the Apache License, Version 2.0

And in NOTICE:

pxCore is Copyright 2015-2018 John Robinson
Licensed under the Apache License, Version 2.0

(iii) There is also a reference to stackoverflow in this file.  In general, we prefer not to use code snippets from online forums.  (stackoverflow content appears to be under CC BY-SA 4.0.)   Given the very boilerplate nature of this code, please will you use different variable names, and instead of referring to stackoverflow, refer to RFC 3986 to credit the regular expression.  (The regexp appears to be slightly modified, perhaps needing C-style backslashes for special characters.)  Please credit RFC3986 with a comment:

 Regular expression from https://tools.ietf.org/html/rfc3986 Appendix B

and in NOTICE,

RFC 3986 is Copyright (C) The Internet Society (2005)
Distribution of this memo is unlimited.


Thank you,
Martin Hughes

**Comment by FitzerIRL** [comment]
> Hi Fitzer,
> Sorry for the delay but this has been a complicated scan. I work in the RDK CMF Compliance Team. I scanned the PR as of some hours ago but the relevant parts have not changed, as far as I can see.
> 
> There are a number of compliance issues with this pull req:
> 
> 
> Where do the image files come from? If they are not original, how are they licensed?
> One image is credited in the readme to https://commons.wikimedia.org/wiki/File:Eo_circle_light-green_white_checkmark.svg
> which is licensed as Creative Commons Attribution-Share Alike 4.0 International (not currently approved and no automatic guarantee of approval.) Trash Can.svg is matching in the scan tool. It is public domain (Clip Art) and probably OK but I will have to request permission.
> So please list all the image files and their source, so we can see what is required. Please be aware that approval or rejection of a new license can take several days.
> 
> 
> Header missing from several files in this directory and below:
> Packager/test/demo/com.comcast.pkgDemo/src/components/
> 
> 
> Please add the following to NOTICE:
> 
> Roboto Regular font is:
> Copyright 2017 Google Inc. All Rights Reserved.
> Licensed under the Apache License, Version 2.0
> 
> 
> Packager/PackagerExUtils.cpp
> Two code matches here:
> (i) A match to libarchive code.
> PackagerExUtils_1
> Probably a reasonable source at https://valadoc.org/libarchive/Archive.Read.html which is licensed the same as the source i.e. BSD-2 according to: https://raw.githubusercontent.com/libarchive/libarchive/master/COPYING. This should be credited, so in the source file round 970, add:
> 
> Copyright (c) 2003-2018 Tim Kientzle
> Licensed under the BSD-2 License
> 
> and in NOTICE, please append the same two lines
> and in LICENSE, no change because there is already a copy of the BSD-2 license there.
> 
> (ii) The pxCore match (which was partially credited but removed): please add back before line 319:
> 
> Based on pxCore, Copyright 2015-2018 John Robinson
> Licensed under the Apache License, Version 2.0
> 
> And in NOTICE:
> 
> pxCore is Copyright 2015-2018 John Robinson
> Licensed under the Apache License, Version 2.0
> 
> (iii) There is also a reference to stackoverflow in this file. In general, we prefer not to use code snippets from online forums. (stackoverflow content appears to be under CC BY-SA 4.0.) Given the very boilerplate nature of this code, please will you use different variable names, and instead of referring to stackoverflow, refer to RFC 3986 to credit the regular expression. (The regexp appears to be slightly modified, perhaps needing C-style backslashes for special characters.) Please credit RFC3986 with a comment:
> 
> Regular expression from https://tools.ietf.org/html/rfc3986 Appendix B
> 
> and in NOTICE,
> 
> RFC 3986 is Copyright (C) The Internet Society (2005)
> Distribution of this memo is unlimited.
> 
> Thank you,
> Martin Hughes


https://trianglify.io/about

**Comment by FitzerIRL** [comment]
> Hi Fitzer,
> Sorry for the delay but this has been a complicated scan. I work in the RDK CMF Compliance Team. I scanned the PR as of some hours ago but the relevant parts have not changed, as far as I can see.
> 
> There are a number of compliance issues with this pull req:
> 
> Where do the image files come from? If they are not original, how are they licensed?
> One image is credited in the readme to https://commons.wikimedia.org/wiki/File:Eo_circle_light-green_white_checkmark.svg
> which is licensed as Creative Commons Attribution-Share Alike 4.0 International (not currently approved and no automatic guarantee of approval.) Trash Can.svg is matching in the scan tool. It is public domain (Clip Art) and probably OK but I will have to request permission.
> So please list all the image files and their source, so we can see what is required. Please be aware that approval or rejection of a new license can take several days.
> 
> Header missing from several files in this directory and below:
> Packager/test/demo/com.comcast.pkgDemo/src/components/
> 
> Please add the following to NOTICE:
> 
> Roboto Regular font is:
> Copyright 2017 Google Inc. All Rights Reserved.
> Licensed under the Apache License, Version 2.0
> 
> Packager/PackagerExUtils.cpp
> Two code matches here:
> (i) A match to libarchive code.
> PackagerExUtils_1
> Probably a reasonable source at https://valadoc.org/libarchive/Archive.Read.html which is licensed the same as the source i.e. BSD-2 according to: https://raw.githubusercontent.com/libarchive/libarchive/master/COPYING. This should be credited, so in the source file round 970, add:
> 
> Copyright (c) 2003-2018 Tim Kientzle
> Licensed under the BSD-2 License
> 
> and in NOTICE, please append the same two lines
> and in LICENSE, no change because there is already a copy of the BSD-2 license there.
> 
> (ii) The pxCore match (which was partially credited but removed): please add back before line 319:
> 
> Based on pxCore, Copyright 2015-2018 John Robinson
> Licensed under the Apache License, Version 2.0
> 
> And in NOTICE:
> 
> pxCore is Copyright 2015-2018 John Robinson
> Licensed under the Apache License, Version 2.0
> 
> (iii) There is also a reference to stackoverflow in this file. In general, we prefer not to use code snippets from online forums. (stackoverflow content appears to be under CC BY-SA 4.0.) Given the very boilerplate nature of this code, please will you use different variable names, and instead of referring to stackoverflow, refer to RFC 3986 to credit the regular expression. (The regexp appears to be slightly modified, perhaps needing C-style backslashes for special characters.) Please credit RFC3986 with a comment:
> 
> Regular expression from https://tools.ietf.org/html/rfc3986 Appendix B
> 
> and in NOTICE,
> 
> RFC 3986 is Copyright (C) The Internet Society (2005)
> Distribution of this memo is unlimited.
> 
> Thank you,
> Martin Hughes


Martin,

I have made numerous updates ... adding Copyright Headers to the JS files,  Creating a NOTICE file with reference you cited.  Additionally adding Image sources - and removing redundant images from the PR

Please let me know what additional changes are necessary, if any.

Thanks for your review and help !

- Hugh

**Comment by FitzerIRL** [comment]
Accidental closure ... reopened

**Comment by mhughesacn** [comment]
Hi Hugh,

Thank you for making these changes.  Our format is a little different so I am going to have to ask you to make a few changes.

NOTICE file:
There is only one NOTICE file and it's in the top level.  So please add lines 1 to 19 from your NOTICE to the end of the top level NOTICE and delete the new one.  I need to look through the images licenses and see what approval is needed from RDK Management/Legal, so these may need to be added later.  (I didn't actually want the list inserted in NOTICE - sorry if I gave that impression.  But the information is just what I need so all good.  However, I still do not have source for:
    Packager/test/demo/com.comcast.pkgDemo/static/images/check_mark80x80.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/crate2_80x80.png
    one of the two files called check_mark.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/hires/crate2 copy.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/hires/info copy.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark copy.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark.png
    Packager/test/demo/com.comcast.pkgDemo/static/images/x_mark80x80.png
)

Packager/PackagerExUtils.cpp
The way RDK gives credit for code snippets is to update top level NOTICE and also to insert the credit in the source file before where the code is used.  So, in PackagerExUtils:

- Please add a credit to Tim Kientzle (around line 976, beside "ARCHIVE CODE") to say:
Copyright (c) 2003-2018 Tim Kientzle
Licensed under the BSD-2 License

- Please delete the two lines at 331 "pxCore is Copyright..." as it is now just a duplicate of the lines above it.  (I appreciate that my instructions were ambiguous!)

I need you to delete line 1195 which gives credit to the stackoverflow link, and instead say:
Regular expression from https://tools.ietf.org/html/rfc3986 Appendix B

and to make the code differ from the stackoverflow version, please use different variable names from url_regex and url_match_result.  This avoids any awkwardness with stackoverflow licensing, as the RFC regex can be used freely, and it is very boilerplate-ish.

One other point: the copyright and compliance scans will continue to object until I clear various matches in our tools, so don't panic when nothing seems to be getting better.

Thanks,
Martin

**Comment by FitzerIRL** [comment]
> Hi Hugh,
> 
> Thank you for making these changes. Our format is a little different so I am going to have to ask you to make a few changes.
> 
> NOTICE file:
> There is only one NOTICE file and it's in the top level. So please add lines 1 to 19 from your NOTICE to the end of the top level NOTICE and delete the new one. I need to look through the images licenses and see what approval is needed from RDK Management/Legal, so these may need to be added later. (I didn't actually want the list inserted in NOTICE - sorry if I gave that impression. But the information is just what I need so all good. However, I still do not have source for:
> Packager/test/demo/com.comcast.pkgDemo/static/images/check_mark80x80.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/crate2_80x80.png
> one of the two files called check_mark.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/hires/crate2 copy.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/hires/info copy.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark copy.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark.png
> Packager/test/demo/com.comcast.pkgDemo/static/images/x_mark80x80.png
> )
> 
> Packager/PackagerExUtils.cpp
> The way RDK gives credit for code snippets is to update top level NOTICE and also to insert the credit in the source file before where the code is used. So, in PackagerExUtils:
> 
> * Please add a credit to Tim Kientzle (around line 976, beside "ARCHIVE CODE") to say:
>   Copyright (c) 2003-2018 Tim Kientzle
>   Licensed under the BSD-2 License
> * Please delete the two lines at 331 "pxCore is Copyright..." as it is now just a duplicate of the lines above it.  (I appreciate that my instructions were ambiguous!)
> 
> I need you to delete line 1195 which gives credit to the stackoverflow link, and instead say:
> Regular expression from https://tools.ietf.org/html/rfc3986 Appendix B
> 
> and to make the code differ from the stackoverflow version, please use different variable names from url_regex and url_match_result. This avoids any awkwardness with stackoverflow licensing, as the RFC regex can be used freely, and it is very boilerplate-ish.
> 
> One other point: the copyright and compliance scans will continue to object until I clear various matches in our tools, so don't panic when nothing seems to be getting better.
> 
> Thanks,
> Martin


**Crate**

Packager/test/demo/com.comcast.pkgDemo/static/images/hires/crate2 copy.png
Packager/test/demo/com.comcast.pkgDemo/static/images/crate2_80x80.png

 SOURCE: https://pixabay.com/vectors/box-crate-wooden-box-wooden-wood-4989961/

**Check** 

Packager/test/demo/com.comcast.pkgDemo/static/images/check_mark80x80.png

SOURCE: https://www.emojipng.com/preview/261669

I *think* this one ...

**X Mark**

Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark copy.png
Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark.png
Packager/test/demo/com.comcast.pkgDemo/static/images/x_mark80x80.png

 SOURCE:  https://creazilla.com/nodes/47245-cross-mark-emoji-clipart  <<< modified:  RED saturation increased.

**Info**

Packager/test/demo/com.comcast.pkgDemo/static/images/hires/info copy.png

Not used... REMOVED

I think that is the LOT ... let me know - I'll be glad to revise further.  

Thanks !

PS:  Whenever I do image searches ... I take care to find license permissive / free ones.

**Comment by FitzerIRL** [comment]
See my comments in reply above.

**Comment by mhughesacn** [comment]
Hi Hugh,
Thank you for making the changes.  About the images, I think we missed one:
Packager/test/demo/com.comcast.pkgDemo/static/images/background.png

and also, are all the check_mark.png files from the same source?  There are 3 different files.  The credit in Packager/test/demo/com.comcast.pkgDemo/README.md is to wikimedia, not to your link but there is a different shade of green in that image.  (Spotting this has to be worth extra marks!)

I appreciate that you have looked for permissive sources but I have to check them out and sometimes the conditions run foul of Legal.

Thanks,
Martin

**Comment by FitzerIRL** [comment]
Martin,

The background.png is something I generated .

https://trianglify.io/

All the check marks are the same source - just scaled.

Totally understand the legal.

No worries,

-Hugh

Sent from my iPhone

On Oct 8, 2020, at 3:33 AM, mhughesacn <notifications@github.com> wrote:

﻿

Hi Hugh,
Thank you for making the changes. About the images, I think we missed one:
Packager/test/demo/com.comcast.pkgDemo/static/images/background.png

and also, are all the check_mark.png files from the same source? There are 3 different files. The credit in Packager/test/demo/com.comcast.pkgDemo/README.md is to wikimedia, not to your link but there is a different shade of green in that image. (Spotting this has to be worth extra marks!)

I appreciate that you have looked for permissive sources but I have to check them out and sometimes the conditions run foul of Legal.

Thanks,
Martin

**Comment by mhughesacn** [comment]
Hi Hugh,
I am collecting the icons licenses to ask Glee Abraham (RDK Management) who will almost certainly kick them to Comcast Legal.  I have looked at the check_mark link (parent of 3 images) which says "License:Non-commercial Use".  This is very vague and unlike to pass muster when it goes for approval.  Given that approvals can take a while, I'd recommend that you look at getting another tick box.  It's a bit hard to say what is approved, so either find other icons under the licenses being requested here (Tango Desktop, pixabay, CC BY 4.0, OpenClipArt) or ask me.
Thanks,
Martin

**Comment by FitzerIRL** [comment]
Any update ?

**Comment by mhughesacn** [comment]
Hi Hugh, I prepared the approval requests on Friday and passed them to Glee for onward submission to legal.  (He didn't want to approve anything himself which is a perfectly reasonable decision.)  I have to tell you that approvals are slow - we would be lucky to get them back by the end of this week.

**Comment by FitzerIRL** [comment]
Any further update ?

**Comment by mhughesacn** [comment]
Sorry Hugh.  We pinged Glee again but it's out of my control.  He does know that you are asking.

**Comment by sverkoye** [comment]
@FitzerIRL , I was trying your lightning pkgDemo app to test and investigate how the "packager progress" events work. But I did not receive any event at all. After some digging in the code I found the cause: you missed something when merging from one of your DAC branches. This is missing inside Packager::Initialize():
`_implementation->Register(&_notification);`

This line: https://github.com/FitzerIRL/rdkservices/blob/58adb8d40fc0bd0916ac9c105b7a62111cbd401e/Packager/Packager.cpp#L54

**Comment by FitzerIRL** [comment]
Stefan,

Nice find !

Indeed I missed it in the merge - thanks for finding it !

I’ve fixed it in the PR - it should update soon.

Best Regards,

-Hugh

Sent from my iPhone

On Oct 27, 2020, at 11:24 AM, Stefan Verkoyen <notifications@github.com> wrote:

﻿

@FitzerIRL<https://github.com/FitzerIRL> , I was trying your lightning pkgDemo app to test and investigate how the "packager progress" events work. But I did not receive any event at all. After some digging in the code I found the cause: you missed something when merging from one of your DAC branches. This is missing inside Packager::Initialize():
_implementation->Register(&_notification);

This line: https://github.com/FitzerIRL/rdkservices/blob/58adb8d40fc0bd0916ac9c105b7a62111cbd401e/Packager/Packager.cpp#L54

**Comment by FitzerIRL** [comment]
Martin,

Any further update ?  

Are we thinking hours / days / weeks to clear legal ?

Folks in the RDK community at large are keen to get this PR merged.

Thanks in advance !

- Hugh

**Comment by mhughesacn** [comment]
Hi Hugh.  I hear you loud and clear!  Legal have it and Glee knows that you need an answer.  I will rattle cages again and look for a resolution timeframe. - Martin

**Comment by mhughesacn** [comment]
Hi Hugh,
I am sorry for the delay in getting back to you after legal approval.  I still have to query one decision but here is what is permitted and what has to be done.  If you find any inconsistencies, please shout.

1. Packager/test/demo/com.comcast.pkgDemo/static/images/sleep80x80.png
This image is an adaptation of an image from Wikimedia licensed as CC-BY-SA 3.0.
Tango have a very permissive license but the original image has specific
conditions that can't be ignored (as Tango appeared to have).  CC BY-SA 3.0
is approved but the image must be in a separate folder ZZZZ, separately licensed
from the rest or rdkservices, which is somewhat laborious.
(You pick the ZZZZs!)
To do this:

(a.) NOTICE needs to change.  First, please use the one in sprint/2010 as the format
has been revised a little across every component - This will go as follows:

```
This component contains software that is Copyright (c) 2018 RDK Management.
The component is licensed to you under the Apache License, Version 2.0 (the "License").
You may not use the component except in compliance with the License.

The component may include material which is licensed under other licenses / copyrights as
listed below. Your use of this material within the component is also subject to the terms and
conditions of these licenses. The LICENSE file contains the text of all the licenses which apply
within this component, except as indicated in the following paragraph.

The ZZZZ directory within this component contains an image which derived from
the GNOME Project and licensed to you under the CC-BY-SA 3.0 License.  The ZZZZ
directory contains its own license file, called LICENSE, which describes the licensing of the
material in the ZZZZ directory.


Copyright (C) 2012 Raphael Kubo da Costa <rakuco@webkit.org>
Licensed under the BSD-2 license

Roboto Regular font is:
Copyright 2017 Google Inc. All Rights Reserved.
Licensed under the Apache License, Version 2.0

RFC 3986 is Copyright (C) The Internet Society (2005)
Distribution of this memo is unlimited.

Ref: https://tools.ietf.org/html/rfc3986


Some code from:-

pxCore is Copyright 2015-2018 John Robinson
Licensed under the Apache License, Version 2.0

libarchive
Copyright (c) 2003-2018 Tim Kientzle
Licensed under the BSD-2 License
```

(b) In ZZZZ, LICENSE should contain the attribution.  To be safe:
```
sleep80x80.png is Copyright (c) 2020 RDK Management and is adapted from an image at:
https://commons.wikimedia.org/wiki/File:Zzz_sleep.svg by the Tango Desktop Project
which is adapted from an image at:
https://commons.wikimedia.org/wiki/File:Face-sleep.svg by the GNOME Project
which is licensed under the Creative Commons Attribution-Share Alike 3.0 Unported License (CC BY-SA 3.0)
```

and then include the text of the license, from: https://creativecommons.org/licenses/by-sa/3.0/legalcode
from "License" to section 8f.

2. Packager/test/demo/com.comcast.pkgDemo/static/images/download3.png
https://pixabay.com/illustrations/download-download-now-download-icon-1915753/
	Packager/test/demo/com.comcast.pkgDemo/static/images/crate2_80x80.png
	Packager/test/demo/com.comcast.pkgDemo/static/images/hires/crate2 copy.png
https://pixabay.com/vectors/box-crate-wooden-box-wooden-wood-4989961/
https://pixabay.com/service/license/
Legal have not allowed this license.  I am chasing this with them because we
used something very similar recently and I am surprised by their decision.
So you can hold tight or replace.


3. Packager/test/demo/com.comcast.pkgDemo/static/images/x_mark80x80.png
	Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark.png
	Packager/test/demo/com.comcast.pkgDemo/static/images/hires/x_mark copy.png
	Packager/test/demo/com.comcast.pkgDemo/static/images/x_mark.png
https://creazilla.com/nodes/47245-cross-mark-emoji-clipart <<< modified: RED saturation increased.
Creative Commons Attribution 4.0 International (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
This is approved.  (Not without a hiccup, as creazilla credit JoyPixels who do not have any images
free for commercial use!  This image is from an earlier set no longer available from JoyPixels and
which had more permissive licensing.)
a. NOTICE entry is:
```
X-mark images adapted from: https://creazilla.com/nodes/47245-cross-mark-emoji-clipart
by JoyPixels (EmojiOne project) which is licensed under the
Creative Commons Attribution 4.0 International License (CC BY 4.0)
```

b. LICENSE needs a copy of the CC BY 4.0 License, use the text at:
https://creativecommons.org/licenses/by/4.0/legalcode, starting at "Creative Commons Attribution 4.0 International Public License" down to 8d.


4. Packager/test/demo/com.comcast.pkgDemo/static/images/TrashCan80x80.png
https://snappygoat.com/s/?q=trash+icon#af3ee7d7f6bbc4788acc3c984ac9c708dfce8a9a,0,8.
Refers to: https://commons.wikimedia.org/wiki/File:Trash_Can.svg
This file is from the Open Clip Art Library, which released it explicitly into the public domain
https://openclipart.org/share
Approved, please(a) add to NOTICE:
```
TrashCan Image originally from: https://commons.wikimedia.org/wiki/File:Trash_Can.svg
Licensed under the Creative Commons Zero 1.0 Public Domain License (CC0 1.0 Universal)
```
b. LICENSE needs to include this license text from https://creativecommons.org/publicdomain/zero/1.0/legalcode
starting at "Statement of Purpose" down to 4(d).
```

**Comment by vijs** [comment]
Closing this PR and we will resubmit it to the latest sprint branch.

**Pull request closed without merging**
